# Generated by Django 5.0.1 on 2024-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='project_name',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
