# Generated by Django 5.0.1 on 2024-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_remove_timesheetentry_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='gender',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='activity',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
